import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const oswald= Oswald({subsets: ["latin"]});

export const outfit= Outfit({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
